### ISSUE TITLE
No such file or directory: "ffmpeg"

### ISSUE THREAD

**Issue by stardust-xr** [tmoroney/auto-subs#33]
Hi! 
I tried to install all the various components which seems successful (I checked for each one if it is), but somehow in DaVinci, it still can't detect ffmpeg, and thus doesn't work. I'm on Mac (Sonoma 14.4.1) so did it through Brew. I've tried multiple things, like reinstalling it, installing the latest version, also downloading ffmepg from the website, but that didn't work (there is a security lock on the file). I tried to find more info on Reddit but haven't found anyone with that specific issue. Any ideas?

<img width="509" alt="Screenshot 2024-04-17 at 18 53 40" src="https://github.com/tmoroney/auto-subs/assets/134049311/08b11cfb-8ef6-44fb-88ea-bab46720bbd5">

**Comment by smlkdev** [comment]
Hey, had the same problem with Sonoma 14.2. Using brew as well. The problem is caused by different binary path hardcoded in the script. Simply open the script with any text editor and replace these lines:

```
  os.environ['FFMPEG'] = '/opt/homebrew/bin/ffmpeg'
  os.environ['PATH'] = '/opt/homebrew/bin:' + os.environ['PATH']
 ```
 
 with proper paths, in my case:
 
 ```
 os.environ['FFMPEG'] = '/usr/local/bin/ffmpeg'
 os.environ['PATH'] = '/usr/local/bin:' + os.environ['PATH']
 ```

Once saved, just reinstall this script by dragging or paste it somewhere into `/Users/_username_/Library/Application Support/Blackmagic Design/DaVinci Resolve/Fusion/Scripts/Utility` dir

You can always check where ffmpeg is installed using:

```
which ffmpeg
```

**Comment by stardust-xr** [comment]
It took me wayyy too long to understand haha (I'm a total beginner so took me a while to understand what the script even was), but it now works! Thanks a lot!
